# Technical documentation

## Configuration file

The configuration file has the following properties.

.Example configuration file
[source,json]
----
{
  "templateDirectory": "full path to the directory with config and templates",
  "sourceDirectory": "directory containing the source",
  "targetDirectory": "directory to write to",
  "indexGenerator": {
    "includeNavigation": true, <1>
    "includeSearch": true, <2>
    "footer": { <3>
      "copyright": "© 2021 Copyright",
      "link": {
        "name": "DocGen",
        "url": "https://github.com/IvoLimmen/DocGen"
      }
    }
  }
}
----
<1> Either `true` or `false`. Will add a nice navigation bar on top.
<2> Either `true` or `false`. Will add a search option in the navigation bar on top. Can be without the navigation.
<3> Adding this part will show a nice footer at the bottom.

## Testing the generated site

When you want to test the features like searching you need to access the generated site using a webserver. 
You can open a terminal, go to the output directory you configured and run:

.Running a webserver
[source,bash]
----
> python3 -m http.server 8080
----

## What does the JSON/YML Swagger to AsciiDoc converter, convert?

The following models from OpenAPI are being converted to AsciiDoc:

* Info
** Title
** Description
** Version
** Contact information
  
* Paths (sorted!)
** Per path the operations if they are present in the following order:
*** delete
*** get
*** head
*** options
*** patch
*** post
*** put
*** trace
* Per operation:
** the current path
** the call (method and path)
** If the method is deprecated (warning)
** Description
** Summary
** RequestBody
*** Description
*** If the body is required
*** Shows object references per media type
** Parameters
*** Lists type, name, description, schema and default
*** Also adds examples in the default column
** Responses
*** Shows object references per media type
*** Currently does not list anonymous types

The following stuff is not (yet?) handled:

  * External examples
  * Headers
  * Security
  * Servers
  * Tags