# Technical documentation

## Overview

Each team in a company that maintains one or multiple project (also called microservices these days) will push all it's documentation and some meta data to a central place.
DocGen will then create a nice index for it.

[graphviz, target="flow", format="png"]
----
digraph flow {
  size ="8.5, 11";

  project1 [shape=record fontname=Arial label="Team1\nproject 1"];
  project2 [shape=record fontname=Arial label="Team1\nproject 2"];
  project3 [shape=record fontname=Arial label="Team2\nproject 3"];
  project4 [shape=record fontname=Arial label="Team2\nproject 4"];

  storage  [shape=record fontname=Arial label="shared drive/website"]
  docgen  [shape=record fontname=Arial label="DocGen"]

  project1 -> storage [label="store"]
  project2 -> storage [label="store"]
  project3 -> storage [label="store"]
  project4 -> storage [label="store"]
  
  storage -> docgen [label="retrieve"]
  docgen -> storage [label="store"]
}
----

## DocGen

### Configuration file

The configuration file has the following properties.

.Example configuration file
[source,json]
----
{
  "indexGenerator": {
    "includeNavigation": true, <1>
    "includeSearch": true, <2>
    "footer": { <3>
      "copyright": "© 2021 Copyright",
      "link": {
        "name": "Zenodotus",
        "url": "https://github.com/IvoLimmen/Zenodotus"
      }
    }
  },
  "tableOfContent": "LEFT", <4>
  "numberedSections": "ON", <5>
  "sourceDirectory": "directory containing the source",
  "targetDirectory": "directory to write to"
}
----
<1> Either `true` or `false`. Will add a nice navigation bar on top.
<2> Either `true` or `false`. Will add a search option in the navigation bar on top. Can be without the navigation.
<3> Adding this part will show a nice footer at the bottom.
<4> Either `LEFT`, `RIGHT`, `PREAMBLE`, `AUTO` to enable table of content for all files, `OFF` to disable, or `AS_DEFINED` by adoc file.
<5> Either `ON` to enable numbered sections for all files, `OFF` to disable, or `AS_DEFINED` by adoc file.

### Testing the generated site

When you want to test the features like searching you need to access the generated site using a webserver. 
You can open a terminal, go to the output directory you configured and run:

.Running a webserver using Python
[source,bash]
----
$ python3 -m http.server 8080
----

or:

.Running a webserver using PHP
[source,bash]
----
$ php -S localhost:8080
----

.Running a webserver using Node
[source,bash]
----
$ npm install -g node-static
$ static -p 8000
----

### What does the JSON/YML Swagger to AsciiDoc converter, convert?

The following models from OpenAPI are being converted to AsciiDoc:

* Info
** Title
** Description
** Version
** Contact information
  
* Paths (sorted!)
** Per path the operations if they are present in the following order:
*** delete
*** get
*** head
*** options
*** patch
*** post
*** put
*** trace
* Per operation:
** the current path
** the call (method and path)
** If the method is deprecated (warning)
** Description
** Summary
** RequestBody
*** Description
*** If the body is required
*** Shows object references per media type
** Parameters
*** Lists type, name, description, schema and default
*** Also adds examples in the default column
** Responses
*** Shows object references per media type
*** Currently does not list anonymous types

The following stuff is not (yet?) handled:

  * External examples
  * Headers
  * Security
  * Servers
  * Tags

## Maven-Analyser

Simply gets all the dependencies from a `pom.xml` by looking at the `DependencyManagement` group.
If you use maven correctly you should have all the dependencies listed there with the version that is used.
The tool does check and resolve properties if your version is a property.

The tool writes a JSON from the analysed data for the DocGen application to use and generate an overview of connected applications.